### ISSUE TITLE
ActionBar - NoSuchMethodError

### ISSUE THREAD

**Issue by jzeferino** [Cheesebaron/SlidingMenuSharp#16]
Hello there.
When i used this library in native android, downloaded directly from market the samples run without problems.
When i used it with xamarin, everything worked but the ActionBar accesses in BaseActivity Line 44:             ActionBar.SetDisplayHomeAsUpEnabled(true);
 throw this exception: "Java.Lang.NoSuchMethodError: getActionBar" on a device with API  2.3.7.
Can you help?

**Comment by thpramos** [comment]
This happens because you don't have the Actionbar on 2.3.7... It was introduced on Honeycomb. 
And... if you are using some kind of compat library or ABS you should change the part "ActionBar" to "SupportActionBar"

Hope it helps! ^^

**Comment by jzeferino** [comment]
yes. i know that. but i tested the native android library with the same device and the action bar worked.
i just read this thread here: https://github.com/Cheesebaron/SlidingMenuSharp/issues/2 and it has some information.

**Comment by Cheesebaron** [comment]
Step 1. Download Support Library v7
Step 2. Follow instructions on how to use it
Step 3. Make a new [`SlidingActivity`](https://github.com/Cheesebaron/SlidingMenuSharp/blob/master/SlidingMenuSharp/App/SlidingActivity.cs) inheriting from `ActionBarActivity` instead of `Activity`
Step 4. ??
Step 5. Profit

Follow these simple steps and you should be golden. Even better just use `NavigationDrawer` from Support v4 instead, makes for a more consistent UI compared to other apps.
